### ISSUE TITLE
Add a options of after application timeout.

### ISSUE THREAD

**Issue by Sraconni** [ArtformGames/VotePass#25]
### **Description**

Add a options of after application timeout.

### **Source**

When the application times out, the next step will not be automatically processed due to insufficient votes.

### **Examples** _(Optional)_

after-timeout: 0/1/2
When = 0, Reserved until staff intervenes in the application.
When = 1, Determined based on the proportion of existing votes.
When = 2, Reject and close the application.

### **AddItional details**

No

**Comment by CarmJos** [comment]
In previous design, there's a option `time.auto-close` to determine the automatic rejection time of a request.

After https://github.com/ArtformGames/VotePass/commit/d2648378668bc2c47fb60d249c450a92900092d0 , I fixed the issues that auto closed reqeusts still be displayed in users' gui.
