### ISSUE TITLE
Game side config file, if the "commands" option is left blank, an error will occur.

### ISSUE THREAD

**Issue by Sraconni** [ArtformGames/VotePass#26]
### **Description**

Game side config file, if the "commands" option is left blank, 
Users cannot process applications normally (approve, reject, abstain) and error will occur.

### **Operatios**

**Step1**
Set the config like:

```text
  commands:
    approve: []
    abstain: []
    reject: []
```

**Or**

```text
  commands:
    approve:
    - ''
    abstain:
    - ''
    reject:
    - ''
```

**Step2**
To process an application, click Approve / Reject.

### **Screenshots & Error Logs**
![votepass-bug#26-image1.jpg](https://s2.loli.net/2023/10/21/x6nkNH4yEjGfDrp.jpg)
![votepass-bug#26-image2.png](https://s2.loli.net/2023/10/21/KCwMtrH1fcNXbVZ.png)

### **Environment**

- System: `Windows 10`
- Java version: `JDK17`
- Minecraft version: `1.20.1`
- Server-core: `purfferfish`

### **Anything else...**

No

**Comment by CarmJos** [comment]
![image](https://github.com/ArtformGames/VotePass/assets/36306882/eb6c2298-658d-4ee2-affb-bceb1ba54f17)
