### ISSUE TITLE
feat(request): Re-submit timeout requests

### ISSUE THREAD

**Issue by Sraconni** [ArtformGames/VotePass#31]
### **Description**

Lobby side, Add a resubmit function, allowing players whose applications have not been processed due to timeout to resubmit without changing the content and inherit the last voting results.

### **Source**

Reduce the cumbersome steps and time-consuming of re-submitting applications for players whose applications were rejected due to timeout.

### **Examples** _(Optional)_

Compare the player's UUID and whether the player has been rejected because the application timeout and was not processed.

**If so**, the player is allowed to choose to submit directly using the last filled-in content when submitting the application, and inherit his last unfinished voting results.

**If so but the player chooses to refill the content**, the application will not inherit the last unfinished voting application and will be regarded as a new application.

This feature is not applicable for new players and players who have been rejected due to voting results.

### **AddItional details**

No

**Comment by CarmJos** [comment]
Will be updated in `1.3.0`.

**Comment by CarmJos** [comment]
Since there is no record in the database of the reason why the request was closed, after deeply consideration, I decided to allow players to view past request content and voting results, whether it was due to "vote rejection" or "timeout closure". Then let themselves to decide whether to modify based on the last request or directly open a new request. 

Requests will not inherit the voting results, so remember to remind players to go to the community groups/forums to attract people to vote for him (Also I think this will stimulate the enthusiasm of the community).

**Comment by CarmJos** [comment]
Test with [VotePass-1.3.0-SNAPSHOT.zip](https://github.com/ArtformGames/VotePass/files/14071380/VotePass-1.3.0-SNAPSHOT.zip)

**Comment by Sraconni** [comment]
> Since there is no record in the database of the reason why the request was closed, after deeply consideration, I decided to allow players to view past request content and voting results, whether it was due to "vote rejection" or "timeout closure". Then let themselves to decide whether to modify based on the last request or directly open a new request.
> 
> Requests will not inherit the voting results, so remember to remind players to go to the community groups/forums to attract people to vote for him (Also I think this will stimulate the enthusiasm of the community).



> Test with [VotePass-1.3.0-SNAPSHOT.zip](https://github.com/ArtformGames/VotePass/files/14071380/VotePass-1.3.0-SNAPSHOT.zip)

Seems like a good idea, but when the rejected player resubmits the application, there seems to be no entrance to use the previous answer, please try to fix it.

**Comment by CarmJos** [comment]
> > Since there is no record in the database of the reason why the request was closed, after deeply consideration, I decided to allow players to view past request content and voting results, whether it was due to "vote rejection" or "timeout closure". Then let themselves to decide whether to modify based on the last request or directly open a new request.
> > Requests will not inherit the voting results, so remember to remind players to go to the community groups/forums to attract people to vote for him (Also I think this will stimulate the enthusiasm of the community).
> 
> > Test with [VotePass-1.3.0-SNAPSHOT.zip](https://github.com/ArtformGames/VotePass/files/14071380/VotePass-1.3.0-SNAPSHOT.zip)
> 
> Seems like a good idea, but when the rejected player resubmits the application, there seems to be no entrance to use the previous answer, please try to fix it.

In this version, i have fixed the issues that gui cannot be used if server have any rules.

Please test it again, thanks~

**Comment by Sraconni** [comment]
> > > Since there is no record in the database of the reason why the request was closed, after deeply consideration, I decided to allow players to view past request content and voting results, whether it was due to "vote rejection" or "timeout closure". Then let themselves to decide whether to modify based on the last request or directly open a new request.
> > > Requests will not inherit the voting results, so remember to remind players to go to the community groups/forums to attract people to vote for him (Also I think this will stimulate the enthusiasm of the community).
> > 
> > 
> > > Test with [VotePass-1.3.0-SNAPSHOT.zip](https://github.com/ArtformGames/VotePass/files/14071380/VotePass-1.3.0-SNAPSHOT.zip)
> > 
> > 
> > Seems like a good idea, but when the rejected player resubmits the application, there seems to be no entrance to use the previous answer, please try to fix it.
> 
> In this version, i have fixed the issues that gui cannot be used if server have any rules.
> 
> Please test it again, thanks~ [VotePass-1.3.0-SNAPSHOT.zip](https://github.com/ArtformGames/VotePass/files/14074974/VotePass-1.3.0-SNAPSHOT.zip)
> 
> https://github.com/ArtformGames/VotePass/actions/runs/7679998527/artifacts/1199796871

Looks great, but there seems to be some issues with placeholder for previous request ID shown on previous request GUI.

**Comment by CarmJos** [comment]
> > > > Since there is no record in the database of the reason why the request was closed, after deeply consideration, I decided to allow players to view past request content and voting results, whether it was due to "vote rejection" or "timeout closure". Then let themselves to decide whether to modify based on the last request or directly open a new request.
> > > > Requests will not inherit the voting results, so remember to remind players to go to the community groups/forums to attract people to vote for him (Also I think this will stimulate the enthusiasm of the community).
> > > 
> > > 
> > > > Test with [VotePass-1.3.0-SNAPSHOT.zip](https://github.com/ArtformGames/VotePass/files/14071380/VotePass-1.3.0-SNAPSHOT.zip)
> > > 
> > > 
> > > Seems like a good idea, but when the rejected player resubmits the application, there seems to be no entrance to use the previous answer, please try to fix it.
> > 
> > 
> > In this version, i have fixed the issues that gui cannot be used if server have any rules.
> > Please test it again, thanks~ [VotePass-1.3.0-SNAPSHOT.zip](https://github.com/ArtformGames/VotePass/files/14074974/VotePass-1.3.0-SNAPSHOT.zip)
> > https://github.com/ArtformGames/VotePass/actions/runs/7679998527/artifacts/1199796871
> 
> Looks great, but there seems to be some issues with placeholder for previous request ID shown on previous request GUI.

Done here https://github.com/ArtformGames/VotePass/actions/runs/7683465705/artifacts/1200272462
